In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = pd.read_csv("diabetes_data.csv")
data

,Patient_ID,Age,Gender,Country,Height_cm,Weight_kg,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,...,PCOS,Medication_Adherence,Work_Type,Residence_Type,Daily_Water_Intake_L,Diabetes_Risk_Score,AI_Health_Recommendation,Doctor_Consultation_Needed,Diabetes_Risk,BMI_CATEGORY
0,1,32.0,Male,Mexico,182.1,65.8,19.8,71.2,88.4,10.4,...,No,Good,Retired,Rural,4.4,60,Healthy Diet Plan,Yes,Moderate,Normal
1,2,42.0,Other,Saudi Arabia,148.5,101.2,45.9,121.8,247.3,11.3,...,Yes,Average,Government,Rural,2.1,99,Begin Diabetes Management Plan,Yes,High,Obese
2,3,89.0,Other,Argentina,158.1,NaN,37.9,131.8,141.9,6.3,...,No,Average,Government,Urban,2.8,80,Strict Blood Sugar Monitoring,Yes,High,Obese
3,4,87.0,Other,United States,190.9,95.9,26.3,99.1,90.1,7.4,...,No,Average,Business,Rural,1.5,82,Begin Diabetes Management Plan,Yes,High,Overweight
4,5,27.0,Other,Australia,156.9,101.9,41.4,77.1,93.8,12.0,...,Yes,Poor,Private,Rural,1.6,93,Begin Diabetes Management Plan,Yes,High,Obese
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,52.0,Female,United Kingdom,153.9,107.4,45.3,75.9,248.8,9.9,...,Yes,Average,Retired,Urban,3.5,86,Consult Endocrinologist Immediately,Yes,High,Obese
49996,49997,53.0,Male,United Kingdom,179.6,64.0,19.8,114.5,198.4,6.3,...,No,Average,Government,Urban,3.4,49,Weight Management Program,No,Moderate,Normal
49997,49998,88.0,Male,Brazil,194.1,65.6,17.4,96.1,118.8,NaN,...,Yes,Poor,Retired,Urban,2.6,100,Begin Diabetes Management Plan,Yes,High,Underweight
49998,49999,23.0,Other,Bangladesh,168.0,73.9,26.2,131.4,139.5,9.2,...,Yes,Good,Private,Urban,2.7,52,Increase Physical Activity,No,Moderate,Overweight
49999,50000,24.0,Female,Australia,152.8,94.6,40.5,66.1,123.5,6.8,...,Yes,Good,Retired,Urban,3.9,91,Consult Endocrinologist Immediately,Yes,High,Obese

In [3]:
data.columns

Index(['Patient_ID', 'Age', 'Gender', 'Country', 'Height_cm', 'Weight_kg',
       'BMI', 'Waist_Circumference_cm', 'Blood_Glucose', 'HbA1c',
       'Fasting_Blood_Sugar', 'Insulin_Level', 'Blood_Pressure_Systolic',
       'Blood_Pressure_Diastolic', 'Total_Cholesterol', 'HDL', 'LDL',
       'Triglycerides', 'Heart_Rate', 'Physical_Activity_Level',
       'Exercise_Hours_Per_Week', 'Daily_Walking_Minutes', 'Diet_Quality',
       'Sugar_Intake_Level', 'Sleep_Hours', 'Stress_Level', 'Smoking_Status',
       'Alcohol_Consumption', 'Family_History_Diabetes', 'Hypertension',
       'Heart_Disease', 'Fatty_Liver', 'PCOS', 'Medication_Adherence',
       'Work_Type', 'Residence_Type', 'Daily_Water_Intake_L',
       'Diabetes_Risk_Score', 'AI_Health_Recommendation',
       'Doctor_Consultation_Needed', 'Diabetes_Risk', 'BMI_CATEGORY'],
      dtype='object')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 42 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient_ID                  50000 non-null  int64
 1   Age                         49503 non-null  float64
 2   Gender                      50000 non-null  object
 3   Country                     50000 non-null  object
 4   Height_cm                   47055 non-null  float64
 5   Weight_kg                   47038 non-null  float64
 6   BMI                         50000 non-null  float64
 7   Waist_Circumference_cm      50000 non-null  float64
 8   Blood_Glucose               49041 non-null  float64
 9   HbA1c                       48026 non-null  float64
 10  Fasting_Blood_Sugar         50000 non-null  float64
 11  Insulin_Level               50000 non-null  float64
 12  Blood_Pressure_Systolic     50000 non-null  int64
 13  Blood_Pressure_Diastolic    50000 non-null  int64
 14  Total_Cholesterol           49000 non-null  float64
 15  HDL                         49000 non-null  float64
 16  LDL                         49000 non-null  float64
 17  Triglycerides               49000 non-null  float64
 18  Heart_Rate                  50000 non-null  int64
 19  Physical_Activity_Level     49500 non-null  object
 20  Exercise_Hours_Per_Week     48008 non-null  float64
 21  Daily_Walking_Minutes       48036 non-null  float64
 22  Diet_Quality                50000 non-null  object
 23  Sugar_Intake_Level          50000 non-null  object
 24  Sleep_Hours                 47983 non-null  float64
 25  Stress_Level                50000 non-null  object
 26  Smoking_Status              50000 non-null  object
 27  Alcohol_Consumption         50000 non-null  object
 28  Family_History_Diabetes     50000 non-null  object
 29  Hypertension                50000 non-null  object
 30  Heart_Disease               50000 non-null  object
 31  Fatty_Liver                 50000 non-null  object
 32  PCOS                        50000 non-null  object
 33  Medication_Adherence        49000 non-null  object
 34  Work_Type                   50000 non-null  object
 35  Residence_Type              50000 non-null  object
 36  Daily_Water_Intake_L        50000 non-null  float64
 37  Diabetes_Risk_Score         50000 non-null  int64
 38  AI_Health_Recommendation    50000 non-null  object
 39  Doctor_Consultation_Needed  50000 non-null  object
 40  Diabetes_Risk               50000 non-null  object
 41  BMI_CATEGORY                50000 non-null  object
dtypes: float64(17), int64(5), object(20)
memory usage: 16.0+ MB

In [5]:
drop_columns = ["Country","Gender","Diabetes_Risk" ,"Doctor_Consultation_Needed", "AI_Health_Recommendation","BMI_CATEGORY","Patient_ID"]

In [6]:
data = data.drop(drop_columns , axis =1)

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       49503 non-null  float64
 1   Height_cm                 47055 non-null  float64
 2   Weight_kg                 47038 non-null  float64
 3   BMI                       50000 non-null  float64
 4   Waist_Circumference_cm    50000 non-null  float64
 5   Blood_Glucose             49041 non-null  float64
 6   HbA1c                     48026 non-null  float64
 7   Fasting_Blood_Sugar       50000 non-null  float64
 8   Insulin_Level             50000 non-null  float64
 9   Blood_Pressure_Systolic   50000 non-null  int64
 10  Blood_Pressure_Diastolic  50000 non-null  int64
 11  Total_Cholesterol         49000 non-null  float64
 12  HDL                       49000 non-null  float64
 13  LDL                       49000 non-null  float64
 14  Triglycerides             49000 non-null  float64
 15  Heart_Rate                50000 non-null  int64
 16  Physical_Activity_Level   49500 non-null  float64
 17  Exercise_Hours_Per_Week   48008 non-null  float64
 18  Daily_Walking_Minutes     48036 non-null  float64
 19  Diet_Quality              0 non-null      float64
 20  Sugar_Intake_Level        50000 non-null  int64
 21  Sleep_Hours               47983 non-null  float64
 22  Stress_Level              50000 non-null  int64
 23  Smoking_Status            50000 non-null  int64
 24  Alcohol_Consumption       0 non-null      float64
 25  Family_History_Diabetes   50000 non-null  object
 26  Hypertension              50000 non-null  object
 27  Heart_Disease             50000 non-null  object
 28  Fatty_Liver               50000 non-null  object
 29  PCOS                      50000 non-null  object
 30  Medication_Adherence      49000 non-null  object
 31  Work_Type                 50000 non-null  object
 32  Residence_Type            50000 non-null  object
 33  Daily_Water_Intake_L      50000 non-null  float64
 34  Diabetes_Risk_Score       50000 non-null  int64
dtypes: float64(20), int64(7), object(8)
memory usage: 13.4+ MB

In [8]:
df_object = data.select_dtypes(include='object')

In [9]:
df_object

,Physical_Activity_Level,Diet_Quality,Sugar_Intake_Level,Stress_Level,Smoking_Status,Alcohol_Consumption,Family_History_Diabetes,Hypertension,Heart_Disease,Fatty_Liver,PCOS,Medication_Adherence,Work_Type,Residence_Type
0,Moderate,Healthy,Low,Moderate,Former,Never,Yes,No,Yes,Yes,No,Good,Retired,Rural
1,High,Healthy,Low,Moderate,Current,Frequently,Yes,No,Yes,Yes,Yes,Average,Government,Rural
2,High,Average,High,High,Never,Frequently,Yes,No,No,Yes,No,Average,Government,Urban
3,High,Average,High,High,Current,Occasionally,Yes,Yes,No,No,No,Average,Business,Rural
4,Moderate,Poor,High,Low,Never,Occasionally,No,Yes,Yes,Yes,Yes,Poor,Private,Rural
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,Low,Poor,Low,Low,Former,Occasionally,Yes,No,No,No,Yes,Average,Retired,Urban
49996,High,Poor,High,Low,Current,Occasionally,No,No,Yes,Yes,No,Average,Government,Urban
49997,Moderate,Poor,High,Moderate,Never,Frequently,Yes,Yes,No,Yes,Yes,Poor,Retired,Urban
49998,Low,Healthy,Moderate,High,Never,Never,No,No,No,Yes,Yes,Good,Private,Urban
49999,Low,Average,Moderate,Moderate,Former,Frequently,No,Yes,No,Yes,Yes,Good,Retired,Urban

In [10]:
df_object.nunique().sum

<bound method Series.sum of Physical_Activity_Level    3
Diet_Quality               3
Sugar_Intake_Level         3
Stress_Level               3
Smoking_Status             3
Alcohol_Consumption        3
Family_History_Diabetes    2
Hypertension               2
Heart_Disease              2
Fatty_Liver                2
PCOS                       2
Medication_Adherence       3
Work_Type                  5
Residence_Type             2
dtype: int64>

In [11]:
status_dict = {'Low': 1, 'Moderate': 2, 'High': 3}
data['Physical_Activity_Level'] = data['Physical_Activity_Level'].map(status_dict)
data['Sugar_Intake_Level'] = data['Sugar_Intake_Level'].map(status_dict)
data['Stress_Level'] = data['Stress_Level'].map(status_dict)

In [14]:
status_dict = {'Poor': 1, 'Average': 2, 'Healthy': 3}
data['Diet_Quality'] = data['Diet_Quality'].map(status_dict)

In [16]:
status_dict = {'Former': 1, 'Current': 2, 'Never': 3}
data['Smoking_Status'] = data['Smoking_Status'].map(status_dict)
data['Alcohol_Consumption'] = data['Alcohol_Consumption'].map(status_dict)

In [17]:
data

,Age,Height_cm,Weight_kg,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,Fasting_Blood_Sugar,Insulin_Level,Blood_Pressure_Systolic,...,Family_History_Diabetes,Hypertension,Heart_Disease,Fatty_Liver,PCOS,Medication_Adherence,Work_Type,Residence_Type,Daily_Water_Intake_L,Diabetes_Risk_Score
0,32.0,182.1,65.8,19.8,71.2,88.4,10.4,149.5,27.4,94,...,Yes,No,Yes,Yes,No,Good,Retired,Rural,4.4,60
1,42.0,148.5,101.2,45.9,121.8,247.3,11.3,199.3,18.3,148,...,Yes,No,Yes,Yes,Yes,Average,Government,Rural,2.1,99
2,89.0,158.1,NaN,37.9,131.8,141.9,6.3,219.6,23.9,101,...,Yes,No,No,Yes,No,Average,Government,Urban,2.8,80
3,87.0,190.9,95.9,26.3,99.1,90.1,7.4,217.7,36.7,120,...,Yes,Yes,No,No,No,Average,Business,Rural,1.5,82
4,27.0,156.9,101.9,41.4,77.1,93.8,12.0,153.5,22.3,190,...,No,Yes,Yes,Yes,Yes,Poor,Private,Rural,1.6,93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,52.0,153.9,107.4,45.3,75.9,248.8,9.9,191.5,15.4,97,...,Yes,No,No,No,Yes,Average,Retired,Urban,3.5,86
49996,53.0,179.6,64.0,19.8,114.5,198.4,6.3,110.0,13.3,121,...,No,No,Yes,Yes,No,Average,Government,Urban,3.4,49
49997,88.0,194.1,65.6,17.4,96.1,118.8,NaN,208.4,30.5,176,...,Yes,Yes,No,Yes,Yes,Poor,Retired,Urban,2.6,100
49998,23.0,168.0,73.9,26.2,131.4,139.5,9.2,84.7,14.8,141,...,No,No,No,Yes,Yes,Good,Private,Urban,2.7,52
49999,24.0,152.8,94.6,40.5,66.1,123.5,6.8,195.3,31.7,166,...,No,Yes,No,Yes,Yes,Good,Retired,Urban,3.9,91

In [18]:
status_dict = {'Frequently': 2, 'Occasionally': 1, 'Never': 3}
data['Alcohol_Consumption'] = data['Alcohol_Consumption'].map(status_dict)

In [22]:
data.dtypes

Age                         float64
Height_cm                   float64
Weight_kg                   float64
BMI                         float64
Waist_Circumference_cm      float64
Blood_Glucose               float64
HbA1c                       float64
Fasting_Blood_Sugar         float64
Insulin_Level               float64
Blood_Pressure_Systolic       int64
Blood_Pressure_Diastolic      int64
Total_Cholesterol           float64
HDL                         float64
LDL                         float64
Triglycerides               float64
Heart_Rate                    int64
Physical_Activity_Level     float64
Exercise_Hours_Per_Week     float64
Daily_Walking_Minutes       float64
Diet_Quality                float64
Sugar_Intake_Level            int64
Sleep_Hours                 float64
Stress_Level                  int64
Smoking_Status                int64
Alcohol_Consumption         float64
Family_History_Diabetes      object
Hypertension                 object
Heart_Disease                object
Fatty_Liver                  object
PCOS                         object
Medication_Adherence         object
Work_Type                    object
Residence_Type               object
Daily_Water_Intake_L        float64
Diabetes_Risk_Score           int64
dtype: object

In [23]:
status_dict = {'Yes': 1, 'No': 0}
data['Family_History_Diabetes'] = data['Alcohol_Consumption'].map(status_dict)
data['Hypertension'] = data['Hypertension'].map(status_dict)
data['Heart_Disease'] = data['Heart_Disease'].map(status_dict)
data['Fatty_Liver'] = data['Fatty_Liver'].map(status_dict)
data['PCOS'] = data['PCOS'].map(status_dict)

In [26]:
data.dtypes

Age                         float64
Height_cm                   float64
Weight_kg                   float64
BMI                         float64
Waist_Circumference_cm      float64
Blood_Glucose               float64
HbA1c                       float64
Fasting_Blood_Sugar         float64
Insulin_Level               float64
Blood_Pressure_Systolic       int64
Blood_Pressure_Diastolic      int64
Total_Cholesterol           float64
HDL                         float64
LDL                         float64
Triglycerides               float64
Heart_Rate                    int64
Physical_Activity_Level     float64
Exercise_Hours_Per_Week     float64
Daily_Walking_Minutes       float64
Diet_Quality                float64
Sugar_Intake_Level            int64
Sleep_Hours                 float64
Stress_Level                  int64
Smoking_Status                int64
Alcohol_Consumption         float64
Family_History_Diabetes     float64
Hypertension                  int64
Heart_Disease                 int64
Fatty_Liver                   int64
PCOS                          int64
Medication_Adherence        float64
Work_Type                    object
Residence_Type                int64
Daily_Water_Intake_L        float64
Diabetes_Risk_Score           int64
dtype: object

In [33]:
status_dict = {'Good': 2, 'Avg': 1,'Poor' : 0}
data['Medication_Adherence'] = data['Medication_Adherence'].map(status_dict)
status_dict = {'Urban' : 0 , 'Rural' :1}
data['Residence_Type'] = data['Residence_Type'].map(status_dict)



data['Work_Type'] = data['Work_Type'].astype('category')

In [34]:
X = data.drop(["Diabetes_Risk_Score" , "Heart_Disease"], axis =1)
Y = data["Diabetes_Risk_Score"]

In [35]:
from sklearn.model_selection import train_test_split

# X represents your features, y represents your target labels
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.23, random_state=42)

In [36]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\aditya mangla\anaconda3\lib\site-packages (3.4.1)
Requirement already satisfied: numpy in c:\users\aditya mangla\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\aditya mangla\anaconda3\lib\site-packages (from xgboost) (1.16.3)

In [37]:
import xgboost as xgb
model = xgb.XGBRegressor(
    objective='reg:squarederror', # Target continuous values
    n_estimators=100,             # Number of boosting rounds
    learning_rate=0.1,            # Step size shrinkage (eta)
    max_depth=5,                  # Maximum tree depth
    random_state=42
)

In [38]:
model.fit(X_train , y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [39]:
from sklearn.metrics import mean_squared_error

predictions = model.predict(X_test)
mse = mean_squared_error(y_test, predictions)
print(f"Mean Squared Error: {mse:.4f}")

Mean Squared Error: 48.5107

In [40]:
import pickle

# Save the trained model to a file
filename = 'model.pkl'
with open(filename, 'wb') as file:
    pickle.dump(model, file)